[project]
name = "api"
version = "0.1.0"
description = "F1 PitWall API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastf1>=3.5.3",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
]

[tool.uv]
package = false
